---
title: Overview
aliases:
  - ../index.html
jupyter:
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

<!-- 
The [foo function](`genominterv.interval_diff`) does ... [](`genominterv.interval_diff`) does ... [](`~genominterv.interval_diff`) does ...
 -->

*genomeinterv* provides support for working with intervals on genomes. A genomic interval is specified as a chromosome, start, and end. It is half-open so that a value `x` is in an interval `(start, end)` included in the inrval if `start <= x and x < end`. All functions take pandas.DataFrame as arguments. These data frames must include `chrom`, `start`, and `end` columns.

See the [the library reference](api/) for detailed documentation of each function and decorator.

## Set operations

The three functions, [](`~genominterv.interval_diff`), [](`~genominterv.interval_intersect`), and [](`~genominterv.interval_union`), do the standard difference, intersection and union set operations on two sets of genomic intervals. The intervals returned from all three functions are collapsed to produce non-overlapping intervals. The genomic intervals in each set must be non-overlapping. This can be achieved using the [](`~genominterv.interval_collapse`) function, which produces the union of genomic intervals in a single set genomic ofintervals.

## Genomic decorator

To make it easy to create other interval functions that work across chromosomes,
the module provides a [](`~genominterv.genomic`) decorator that can be applied to functions
that operate lists of `(start, end)` tuples. Applying the decorator changes
the signature of a function to make it operate on DataFrames that include
`chrom`, `start`, and `end` columns. Here is an example function that
shifts intervals by 1000bp:

```python
@genomic
def inverval_shift(tuples):
    return [(x+1000, y+1000) for (x, y) in tuples]

df = pandas.DataFrame()

shifted = inverval_shift(df)
```  

## Remapping functions

The function [](`~genominterv.interval_distance`) converts coordinates of one set of
genomic intervals into distances to the closest interval in a second set.
[](`~genominterv.interval_relative_distance`) does the same but returns
relative distances.

## Two-set statistics

The module also provides two statistics for relations between sets:
[](`~genominterv.jaccard`) computes the [Jaccard index](https://en.wikipedia.org/wiki/Jaccard_index)
statistic for two sets of genomic intervals.


## Bootstrap decorator

The module provides a [](`~genominterv.bootstrap`) decorator that turns a function producing
a statistic into one that also produces a p-value. The bootstrapping resamples
the intervals of the second argument for each chromosome independently. Only
required argument to bootstrap is the name of the chromosome assembly used.

This example does this for the provided [](`~genominterv.jaccard`) statistic

```python
@bootstrap('hg19', samples=1000)
def jaccard_test(query, annot):
    return jaccard(query, annot)

jaccard_stat, p_value = jaccard_test(intervals, other_intervals)
```

The decorator works on any function that takes two sets of intervals.


## Ready-made tests

[](`~genominterv.proximity_test`) computes tests if intervals in one set is significantly
proximal to intervals in another set.

## Learning more

Go [to the anvanced page](advanced.qmd) to learn how to ...

* [Examples page](examples.ipynb): sites using quartodoc.

