{% set data = load_setup_py_data() %}

package:
  name: genominterv
  version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/genominterv.git

build:
  # noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:       # write here the list of your library dependencies
    - python
    - pandas
    - numpy
    - statsmodels
    - matplotlib

channels:    # write here the list of channels to look for your library dependencies
  # - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  - conda-verify
  
test:
  imports:
    - genominterv
  # commands:
  #   - exercises --help    

about:
  home: https://github.com/munch-group/genominterv.git
  license: MIT
  # summary: "Blah blah"
  # description: |
  #   "Blah blah"
  #   "Blah blah"
  dev_url: https://github.com/munch-group/genominterv.git
  doc_url: https://munch-group.org/genominterv
