# Function reference {.doc .doc-index}

## Genomic set operations

Set operations on pandas.DataFrames with columns for chromosome, start, and end.


| | |
| --- | --- |
| [interval_diff](interval_diff.qmd#genominterv.interval_diff) | This function computes the difference between two sets of genomic intervals. |
| [interval_union](interval_union.qmd#genominterv.interval_union) | This function computes the union of two sets of genomic intervals. The genomic intervals |
| [interval_intersect](interval_intersect.qmd#genominterv.interval_intersect) | This function computes the intersection of two sets of genomic intervals. The genomic intervals |
| [interval_collapse](interval_collapse.qmd#genominterv.interval_collapse) | This function computes the union of intervals in a single set. |

## Remapping

Mapping intervals relative to other coordinates.


| | |
| --- | --- |
| [interval_distance](interval_distance.qmd#genominterv.remapping.interval_distance) | Computes the distance from each query interval to the closest interval in |
| [remap_interval_data](remap_interval_data.qmd#genominterv.remapping.remap_interval_data) | Computes the distance from each query interval to the closest interval |

## Statistics

Mapping intervals relative to other coordinates.

| | |
| --- | --- |
| [proximity_test](proximity_test.qmd#genominterv.stats.proximity_test) | Test for proximity of intervals to a set of annotations. |
| [jaccard_stat](jaccard_stat.qmd#genominterv.stats.jaccard_stat) | Compute Jaccard overlap test statistic. |

## Decorators

Utilities for user created genomic intervals and bootstrap tests.


| | |
| --- | --- |
| [genomic](genomic.qmd#genominterv.decorators.genomic) | Decorator for converting a function operating on lists of (start, end) tuples to one |
| [bootstrap](bootstrap.qmd#genominterv.decorators.bootstrap) | Parameterized decorator that turns a function producing a statistic into one that also |

## Interval set utilities

Set operations on sorted lists of (start, end) tuples.


| | |
| --- | --- |
| [union](union.qmd#genominterv.interval_set_op.union) | Union intervals of two sorted lists of (start, end) intervals. |
| [diff](diff.qmd#genominterv.interval_set_op.diff) | Difference intervals of two sorted lists of (start, end) intervals. |
| [invert](invert.qmd#genominterv.interval_set_op.invert) | Produces the complement of a list of sorted intervals  |
| [intersect](intersect.qmd#genominterv.interval_set_op.intersect) | Intersection intervals of two sorted lists of (start, end) intervals. |
| [collapse](collapse.qmd#genominterv.interval_set_op.collapse) | Converts a list of sorted overlapping intervals to non-overlapping |

## Interval mapping utilities

Set operations on sorted lists of (start, end) tuples.


| | |
| --- | --- |
| [remap](remap.qmd#genominterv.remapping.remap) | Remap the coordinates of a single interval in `query` to the distance from |