project:
  type: website
  output-dir: _build
  resources:
    - examples/single-page
    - examples/pkgdown
    - examples/auto-package
    # - objects.txt
    # - objects-test.txt

execute:
  freeze: auto
  echo: true

metadata-files:
  - api/_sidebar.yml

filters:
  - "interlinks"

interlinks:
  fast: true
  sources:
    python:
      url: https://docs.python.org/3/
    pandas:
      url: https://pandas.pydata.org/docs/
    griffe:
      url: https://mkdocstrings.github.io/griffe/
    numpy:
      url: https://numpy.org/doc/stable/
    # quartodoc-test:
    #   url: https://machow.github.io/quartodoc
    #   inv: objects-test.txt

website:
  title: "genominterv"
  page-navigation: true
  navbar:
    left:
      # - file: examples/
      #   text: Examples
      - href: api/
        text: Reference
    right:
      - icon: github
        href: https://github.com/munch-group/genominterv/
  sidebar:
    - id: pages
      title: Get Started
      style: floating
      align: left
      contents:
        - pages/getting_started.qmd
        - section: "Set operations"
          contents:
            - pages/set_operations.ipynb
            - pages/decorators.ipynb
        - section: "Mapping"
          contents:
            - pages/interval_tests.ipynb
            - pages/mapping.ipynb
        - section: "Examples"
          contents:
            - examples/examples.ipynb            
        - section: "Library reference"
          contents:
            - api/index.qmd

format:
  html:
    theme: cosmo
    css:
      - api/_styles-quartodoc.css
      - styles.css
    # highlight-style: breeze 
    highlight-style: github 
    code-block-bg: true
    # toc: true
    mermaid:
      theme: neutral 

quartodoc:
  style: pkgdown
  dir: api
  package: genominterv
  render_interlinks: true
  options:
    signature_name: full
  renderer:
    style: markdown
    table_style: description-list
  sidebar: "api/_sidebar.yml"
  css: "api/_styles-quartodoc.css"

  sections:
    - title: Genomic set operations
      desc: "Set operations on pandas.DataFrames with `chrom`, `start`, `end` columns"
      package: genominterv.intervals
      contents:
        - interval_diff     
        - interval_union   
        - interval_intersect 
        - interval_collapse
        - interval_distance
    - title: Mapping
      package: genominterv.intervals
      desc: "Mapping intervals relative to other coordinates."
      contents:        
        - interval_relative_distance
        - remap_interval_data
    - title: Statistics
      package: genominterv.stats
      desc: "Mapping intervals relative to other coordinates."
      contents:
        - proximity_test        
        - jaccard_stat
    - title: Decorators
      desc: "Utilities for user created genomic intervals and bootstrap tests."
      package: genominterv.decorators
      contents:
        - genomic 
        - bootstrap
    - title: Interval set utilities
      desc: "Set operations on sorted lists of (start, end) tuples."
      package: genominterv.interval_set_op
      contents:
        - union 
        - diff
        - invert
        - intersect
        - collapse
    - title: Interval mapping utilities
      desc: "Set operations on sorted lists of (start, end) tuples."
      package: genominterv.remapping
      contents:
        - remap 
